// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_ALIGNOF_HPP_INCLUDED
#define COMP_FOONATHAN_ALIGNOF_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_ALIGNOF 1




#ifndef FOONATHAN_ALIGNOF
    #if FOONATHAN_HAS_ALIGNOF
        #define FOONATHAN_ALIGNOF(x) alignof(x)
    #elif defined(_MSC_VER)
        #define FOONATHAN_ALIGNOF(x) __alignof(x)
    #elif defined(__GNUC__)
        #define FOONATHAN_ALIGNOF(x) __alignof__(x)
    #else
        #error "no alignof replacement available"
    #endif
#endif


#endif
