// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_GET_NEW_HANDLER_HPP_INCLUDED
#define COMP_FOONATHAN_GET_NEW_HANDLER_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_GET_NEW_HANDLER 1



#include <new>

namespace foonathan_comp
{
#if FOONATHAN_HAS_GET_NEW_HANDLER
    inline std::new_handler get_new_handler()
    {
        return std::get_new_handler();
    }
#else
    inline std::new_handler get_new_handler()
    {
        std::new_handler h = std::set_new_handler(0);
        std::set_new_handler(h);
        return h;
    }
#endif
}

#endif
