// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_MAX_ALIGN_T_HPP_INCLUDED
#define COMP_FOONATHAN_MAX_ALIGN_T_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_MAX_ALIGN_T 1



namespace foonathan_comp
{
#if FOONATHAN_HAS_MAX_ALIGN_T
    namespace max_align
    {
        using namespace std; // might not be in namespace std
        typedef max_align_t type;
    }

    typedef max_align::type max_align_t;
#else
    // this struct should have maximum alignment
    struct max_align_t
    {
        long double ld;
        long long ll;
    };
#endif
}

#endif
