// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_MUTEX_HPP_INCLUDED
#define COMP_FOONATHAN_MUTEX_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_MUTEX 1





#endif
