// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_NOEXCEPT_HPP_INCLUDED
#define COMP_FOONATHAN_NOEXCEPT_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_NOEXCEPT 1


#if FOONATHAN_HAS_NOEXCEPT
    #if !defined(__cpp_noexcept)
        #define __cpp_noexcept 201003
    #elif 201003 > __cpp_noexcept
        #undef __cpp_noexcept
        #define __cpp_noexcept 201003
    #elif defined(COMP_OVERRIDE_SD6)
        #undef __cpp_noexcept
        #define __cpp_noexcept 201003
    #endif
#endif

#ifndef FOONATHAN_NOEXCEPT
    #if FOONATHAN_HAS_NOEXCEPT
        #define FOONATHAN_NOEXCEPT noexcept
    #else
        #define FOONATHAN_NOEXCEPT
    #endif
#endif

#ifndef FOONATHAN_NOEXCEPT_IF
    #if FOONATHAN_HAS_NOEXCEPT
        #define FOONATHAN_NOEXCEPT_IF(x) noexcept(x)
    #else
        #define FOONATHAN_NOEXCEPT_IF(x)
    #endif
#endif

#ifndef FOONATHAN_NOEXCEPT_OP
    #if FOONATHAN_HAS_NOEXCEPT
        #define FOONATHAN_NOEXCEPT_OP(x) noexcept(x)
    #else
        #define FOONATHAN_NOEXCEPT_OP(x) false
    #endif
#endif

#endif
