// This file was autogenerated using foonathan/compatibility.
// See https://github.com/foonathan/compatibility for further information.
// Do not edit manually!

#ifndef COMP_FOONATHAN_RVALUE_REF_HPP_INCLUDED
#define COMP_FOONATHAN_RVALUE_REF_HPP_INCLUDED

#include <cstddef>

#define FOONATHAN_HAS_RVALUE_REF 1


#if FOONATHAN_HAS_RVALUE_REF
    #if !defined(__cpp_rvalue_references)
        #define __cpp_rvalue_references 200610
    #elif 200610 > __cpp_rvalue_references
        #undef __cpp_rvalue_references
        #define __cpp_rvalue_references 200610
    #elif defined(COMP_OVERRIDE_SD6)
        #undef __cpp_rvalue_references
        #define __cpp_rvalue_references 200610
    #endif
#endif



#endif
